language: node_js

script: yarn && yarn common-check && yarn build

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: dist
  github-token: $GH_TOKEN
  on:
    branch: master

cache: yarn

notifications:
  email: false
